---
- name: Disable service apache
  become: yes
  systemd:
    name: apache2
    enabled: no
    state: stopped

- name: Ensure nginx is at the latest version
  become: yes
  apt: name=nginx state=latest

- name: Enable service nginx
  become: yes
  systemd:
    name: nginx
    enabled: yes
    state: started
