###########################################################################################################
# Playbook: WP Install
###################################################################################################################

---
- name: ConfigureSsh
  hosts: main
  remote_user: root
  gather_facts: false
  tags:
    - ssh
  roles:
    - configure_ssh_port

- name: ConfigureBase
  hosts: main
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/global.yml
  vars:
    create_user: "{{ lookup('vars', 'username') }}"
    create_user_password: "{{ lookup('env', 'USER_PASSWORD_ENCRYPTED') }}"
  tags:
    - base
  roles:
    - base

- name: InstallZsh
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  become_method: sudo
  vars_files:
    - vars/global.yml
  vars:
    oh_my_zsh_install: yes
    zsh_antigen_bundles_extras:
      - joel-porquet/zsh-dircolors-solarized
  tags:
    - zsh
  roles:
    - viasite-ansible.zsh
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ lookup('vars', 'username') }}"

- name: InstallWP
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  become_method: sudo
  vars_files:
    - vars/global.yml
  vars:
  tags:
    - wp
  roles:
