###########################################################################################################
# Playbook: WP Install
###################################################################################################################

---
- name: ConfigureSsh
  hosts: main
  remote_user: root
  gather_facts: false
  tags:
    - ssh
  roles:
    - configure_ssh_port

- name: ConfigureBase
  hosts: main
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/global.yml
  vars:
    create_user: "{{ lookup('vars', 'username') }}"
    create_user_password: "{{ lookup('env', 'USER_PASSWORD') | password_hash('sha512') }}"
  tags:
    - base
  roles:
    - base

- name: InstallZsh
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  vars_files:
    - vars/global.yml
  vars:
    oh_my_zsh_install: yes
    zsh_antigen_bundles_extras:
      - joel-porquet/zsh-dircolors-solarized
  tags:
    - zsh
  roles:
    - role: viasite-ansible.zsh
      zsh_user: "{{ lookup('vars', 'username') }}"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ lookup('vars', 'username') }}"

- name: InstallMysql
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  vars_files:
    - vars/global.yml
  vars:
    - mariadb_root_password: "{{ lookup('env', 'MYSQL_DB_ROOT_PASS') }}"
    - mariadb_databases:
      - name: "{{ lookup('env', 'MYSQL_DB_NAME') }}"
    - mariadb_users:
      - name: "{{ lookup('env', 'MYSQL_DB_USER') }}"
        password: "{{ lookup('env', 'MYSQL_DB_USER_PASS') }}"
        priv: "{{ lookup('env', 'MYSQL_DB_NAME') }}.*:ALL"
        append_privs: 'yes'
  tags:
    - mysql
  roles:
    - mysql

- name: InstallPhp
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  vars_files:
    - vars/global.yml
  tags:
    - php
  roles:
    - php74
    - sbaerlocher.wp-cli
    - geerlingguy.composer

- name: InstallNodejs
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  vars_files:
    - vars/global.yml
  tags:
    - nodejs
  roles:
    - nodejs

- name: InstallNginx
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  vars_files:
    - vars/global.yml
  tags:
    - nginx
  roles:
    - nginx

- name: InstallWP
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  vars_files:
    - vars/global.yml
  vars:
    mysql_db: "{{ lookup('env', 'MYSQL_DB_NAME') }}"
    mysql_user: "{{ lookup('env', 'MYSQL_DB_USER') }}"
    mysql_password: "{{ lookup('env', 'MYSQL_DB_USER_PASS') }}"
    domain_name_zone: "{{ lookup('env', 'DOMAIN_NAME_ZONE') }}"
    domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
    www_domain_name: "www.{{ lookup('env', 'DOMAIN_NAME') }}"
    acme_email: "{{ lookup('env', 'ACME_EMAIL_ADDRESS') }}"
    cloudflare_account_api_key: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_API_KEY') }}"
    cloudflare_account_email: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_EMAIL') }}"
    letsencrypt_keys_dir: /etc/letsencrypt/keys
    letsencrypt_certs_dir: /etc/letsencrypt/certs
    wordpress_url: "{{ lookup('env', 'WORDPRESS_URL') }}"
    wordpress_title: "{{ lookup('env', 'WORDPRESS_TITLE') }}"
    wordpress_user: "{{ lookup('env', 'WORDPRESS_USER') }}"
    wordpress_pass: "{{ lookup('env', 'WORDPRESS_PASS') }}"
    wordpress_email: "{{ lookup('env', 'WORDPRESS_EMAIL') }}"
  roles:
    - letsencrypt
    - wordpress
  tags:
    - wp
