###########################################################################################################
# Playbook: WP Install
###################################################################################################################

---
- name: ConfigureSsh
  hosts: main
  remote_user: root
  gather_facts: false
  tags:
    - ssh
  roles:
    - configure_ssh_port

- name: ConfigureBase
  hosts: main
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/global.yml
  vars:
    create_user: "{{ lookup('vars', 'username') }}"
    create_user_password: "{{ lookup('env', 'USER_PASSWORD_ENCRYPTED') }}"
  tags:
    - base
  roles:
    - base

- name: InstallZsh
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: "{{ ansible_user }}"
  vars_files:
    - vars/global.yml
  vars:
    oh_my_zsh_install: yes
    zsh_antigen_bundles_extras:
      - joel-porquet/zsh-dircolors-solarized
  tags:
    - zsh
  roles:
    - role: viasite-ansible.zsh
      zsh_user: "{{ lookup('vars', 'username') }}"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ lookup('vars', 'username') }}"

- name: InstallMysql
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  become_method: sudo
  vars_files:
    - vars/global.yml
  vars:
    - mariadb_root_password: "{{ lookup('env', 'MYSQL_DB_ROOT_PASS') }}"
    - mariadb_databases:
      - name: "{{ lookup('env', 'MYSQL_DB_NAME') }}"
    - mariadb_users:
      - name: "{{ lookup('env', 'MYSQL_DB_USER') }}"
        password: "{{ lookup('env', 'MYSQL_DB_USER_PASS') }}"
        priv: "{{ lookup('env', 'MYSQL_DB_NAME') }}.*:ALL"
        append_privs: 'yes'
  tags:
    - mysql
  roles:
    - mysql

- name: InstallPhp
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  become_method: sudo
  vars_files:
    - vars/global.yml
  tags:
    - php
  roles:
    - php74

- name: InstallNginx
  hosts: main
  remote_user: "{{ lookup('vars', 'username') }}"
  gather_facts: true
  become: yes
  become_method: sudo
  vars_files:
    - vars/global.yml
  tags:
    - nginx
  roles:
    - nginx

    # TODO
    # - nodejs
    # - composer
    # - Wordpress
