---
acme_challenge_type: dns-01
acme_directory: https://acme-v02.api.letsencrypt.org/directory
acme_version: 2
acme_email: certificate-reminders@your-domain
letsencrypt_dir: /etc/letsencrypt
letsencrypt_keys_dir: /etc/letsencrypt/keys
letsencrypt_csrs_dir: /etc/letsencrypt/csrs
letsencrypt_certs_dir: /etc/letsencrypt/certs
letsencrypt_account_key: /etc/letsencrypt/account/account.key
domain_name_zone: your-domain.com
domain_name: your-domain.com
www_domain_name: www.your-domain.com
cloudflare_account_api_key: seek-from-cloudflare-dashboard
cloudflare_account_email: cloudflare@email
