---
- name: Add the packages in sources lists
  become: true
  shell: wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
  when: ansible_os_family == 'Debian'

- name: Add the packages in sources lists
  become: true
  shell: sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
  when: ansible_os_family == 'Debian'

- name: Update packages
  become: true
  apt:
    update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install PHP
  apt:
    name: "{{ php_core_packages }}"
    state: present

- name: Install PHP Extensions
  apt:
    name: "{{ php_extension_packages }}"
    state: present

- name: Update PHP ini
  community.general.ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: 'PHP'
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items: "{{ php_ini_updates }}"
  notify: restart php-fpm

- name: Creating error log
  file:
    path: "{{ php_error_log }}"
    state: touch
    mode: 0755
    owner: www-data
