php_core_packages:
  - php7.4
  - php7.4-common
  - php7.4-cli
php_extension_packages:
  - php7.4-fpm
  - php7.4-mysql
  - php7.4-curl
  - php7.4-gd
  - php7.4-mbstring
  - php7.4-xml
  - php7.4-xmlrpc
