---
mariadb_packages:
  - mariadb-common
  - mariadb-server
  - python3-pymysql

mariadb_socket: /var/run/mysqld/mysqld.sock

mariadb_config_network: /etc/mysql/conf.d/network.cnf
mariadb_config_server: /etc/mysql/conf.d/server.cnf
mariadb_config_custom: /etc/mysql/conf.d/custom.cnf
mariadb_config_logrotate: /etc/logrotate.d/mysql
