---

- name: InstallMysql
  hosts: webservers
  remote_user: "{{ system_user }}"
  gather_facts: true
  become: yes
  vars:
    - mariadb_root_password: "{{ db_root_password }}"
    - mariadb_databases:
      - name: "{{ db_name }}"
    - mariadb_users:
      - name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: "{{ db_name }}.*:ALL"
        append_privs: 'yes'
  tags:
    - install-mysql
  roles:
    - mysql
