---

- name: InstallWP
  hosts: webservers
  remote_user: "{{ system_user }}"
  gather_facts: true
  vars:
    mysql_db: "{{ db_name }}"
    mysql_user: "{{ db_user }}"
    mysql_password: "{{ db_user_password }}"
    wordpress_title: "{{ site_title }}"
    wordpress_user: "{{ site_user }}"
    wordpress_password: "{{ site_password }}"
    wordpress_email: "{{ site_email }}"
  roles:
    - wordpress
  tags:
    - install-wordpress
