---

- name: InstallZsh
  hosts: webservers
  remote_user: "{{ system_user }}"
  gather_facts: true
  become: yes
  vars:
    oh_my_zsh_install: yes
    zsh_antigen_bundles_extras:
      - joel-porquet/zsh-dircolors-solarized
  tags:
    - install-zsh
  roles:
    - role: viasite-ansible.zsh
      zsh_user: "{{ system_user }}"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ system_user }}"
